name: QA Pipeline

on:
  pull_request:
    branches:
      - DEV

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and deploy to QA
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID_QA }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}
          branch: DEV
          env: QA
          render-url: "https://qa.example.com"
